### ISSUE TITLE
Linux x86_64 wheel for Python 3.11

### ISSUE THREAD

**Issue by claird-ot** [jnwatson/py-lmdb#335]
Linux **x86_64 wheel** for Python 3.11

### Affected Operating Systems

* Linux

### Affected py-lmdb Version

    3.11

### py-lmdb Installation Method

    wheel

### Describe Your Problem

This project publishes **wheel**-s for Python 3.10, 3.9, ... for Linux **x86_64**.  This project publishes **wheel**-s for Python 3.11 for MacOS and Windows.  How can I help publication of the **wheel** for 3.11 for Linux **x86_64**?

**Comment by vEpiphyte** [comment]
@jnwatson It appears the project is missing a build directive for a python 3.11 wheel here https://github.com/jnwatson/py-lmdb/blob/master/.github/workflows/python-package.yml#L159

**Comment by claird-ot** [comment]
Will a **pull request** from us help resolve publication of the **wheel** for 3.11, @jnwatson?

**Comment by jnwatson** [comment]
No need. @vEpiphyte pointed out the issue.

**Comment by jnwatson** [comment]
Well, I spoke too soon. It looks like we have an upstream CI problem: https://github.com/RalfG/python-wheels-manylinux-build/issues/63. I'm blocked on that.

**Comment by claird-ot** [comment]
I don't like `lmdb`'s 3.11-less-ness.  I _do_ appreciate the updates, Nic.  Thanks for keeping us current, and let us know what helps you.

**Comment by jnwatson** [comment]
Well, you can still use 3.11, you just have to build from source.

**Comment by jnwatson** [comment]
Looks like the about manylinux CI module isn't being maintained. Looks like the new hotness is https://github.com/pypa/cibuildwheel.

I'll give it a couple days. If no movement, I'll have to port to the new system. PRs definitely welcome.

**Comment by claird-ot** [comment]
"... you just have to build from source":  absolutely true, and worth repeating.

I repeat:  thanks, Nic, for the updates.

**Comment by jnwatson** [comment]
On a third look, I found the problem.

**Comment by jnwatson** [comment]
Fixed in #339 and merged to master.

**Comment by claird** [comment]
I appreciate the progress, Nic.

This does _not_ appear **completed** to me, in the sense that [the project file](https://pypi.org/project/lmdb/#files) still shows that the only 3.11 Linux wheel is for ARM, not x86.

**Comment by vEpiphyte** [comment]
I believe a v1.4.1 tag would kick the build machines for everything?

**Comment by jnwatson** [comment]
That's correct.
